### ISSUE TITLE
Info about fetching includes

### ISSUE THREAD

**Issue by rpunkfu** [tj/mmake#12]
Right now if we run Makefile via `mmake`  for the first time it fetches github.com includes, it might be cool to have some kind of info / spinner running, dunno..

Since this exists, might as well be used here: https://github.com/tj/go-spin :p

**Comment by tj** [comment]
Possibly! They're near instant for me but I guess I have a decent connection, a spinner might look more like a weird artifact if it just flashes

**Comment by rpunkfu** [comment]
Good point, for me it's also really fast, was thinking about users with slower connection, but how long can it be hah. Spinner would indeed look weird as I think about it now..

**Comment by zph** [comment]
Nice suggestion and happy to consider this if a user w/ slower connection is interested in putting together a PR. Closing since it's had no movement in 2 years.
