### ISSUE TITLE
Local includes are not working as intended

### ISSUE THREAD

**Issue by gmcabrita** [tj/mmake#13]
Consider two local files `Makefile` and `foo.mk`

Makefile:
```Makefile
include foo.mk
```

foo.mk
```Makefile
foo:
	@echo "foo"
```

`make` allows including the local file, but `mmake` seems to think it's a remote include.

```shell
$ make foo
foo
$ mmake foo
   ⨯ installing                error=installing "foo.mk": only github.com is currently supported
```

**Comment by tj** [comment]
oops, great thing to forget to test :D
