### ISSUE TITLE
Resolve in local includes

### ISSUE THREAD

**Issue by tj** [tj/mmake#14]
Currently just ignoring them entirely, but ideally we traverse those as well and pick up any local includes / comments.

**Comment by azer** [comment]
+1, [Makefiles including .env files](https://github.com/azer/go-preact-starter/blob/master/Makefile#L1) fails currently.

**Comment by matthewp** [comment]
Running `make help` doesn't include items within includes, does this issue cover that?

**Comment by tj** [comment]
It should resolve help for anything included from github.com, but not local to the project for example, though I never do that personally.
